name: Publish Github Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  pages: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Security Agent
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            pipelines.actions.githubusercontent.com:443

      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@c03b5dbed22245418539b65eb9a3b1d5fdd9a0a6
        with:
          hugo-version: 0.104.0
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@45efe609374726fd94570f0e5a4c32f41675e823

      - name: Hugo Build
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --baseURL "${{ steps.pages.outputs.base_url }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@a597aecd27af1cf14095ccaa29169358e3d91e28
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          path: ./public

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Install Security Agent
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: audit
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@44d42469122ee9e44e202f0a0fab6f266fb3f139
